### ISSUE TITLE
Homepage: DiscordSection component

### ISSUE THREAD

**Issue by Drorka** [Bootcamp-Projects-Hamechina/hamechina#20]
Create the discord section component (הדיסקורד).
path: app/(routes)/(homepage-sections)/_discord-section/index.tsx

See the Figma design: https://www.figma.com/file/Duqi7NP9cmnhVoQHJPyXGD/Hamechina?type=design&node-id=0%3A1&mode=design&t=9meolVcvbbpcYwRU-1

Link to component: [app/(routes)/(homepage-sections)/_discord-section/index.tsx](https://github.com/Bootcamp-Projects-Hamechina/hamechina/blob/main/app/(routes)/(homepage-sections)/_discord-section/index.tsx)

**Comment by SathvikKandadi** [comment]
Hey can you assign me this issue?

**Comment by amabelleS** [comment]
> Hey can you assign me this issue?

Hey @SathvikKandadi :) Thank you, I'll assign this issue to you. 

Here is a screenshot of the light mood version from Figma, to get you started:
<img width="562" alt="image" src="https://github.com/Bootcamp-Projects-Hamechina/hamechina/assets/45571546/c8fe4d74-e191-4db1-864b-6d3217e3057f">
 
 You can use lorem ipsum instead of the Hebrew text.

**Comment by SathvikKandadi** [comment]
Hey how can I contact you ?

**Comment by amabelleS** [comment]
> Hey how can I contact you?

Here is fine. Or email: amabelletr@gmail.com
And there is a discord channel: https://discord.gg/PAYc4nTM

**Comment by amabelleS** [comment]
Playing with builder.io 💯
